### ISSUE TITLE
qc.and.removeDoublets

### ISSUE THREAD

**Issue by jozefiendeclercq** [paiva-s-lab/FlowCT#8] opened 2023-10-12 15:24 UTC
Hi,
I would like to use a FlowCT workflow on my 26-parameter flowcytometry dataset, but I am running into a problem with quality control.
When I use the function "qc.and.removeDoublets" function on a SCE object of 27.3 MB (4 fcs files) I get the following error "Error: cannot allocate vector of size 292.4 Gb". I am running the code on a PC with 64.0 GB  installed RAM and already increased the R memory available. I noticed that a similar error is generated when running the "flow_auto_qc()" function from the flowAI package.
How can I resolve this problem?
Thanks!

**Comment by jgarces02** [comment] 2023-10-17 19:26
Hi @jozefiendeclercq, I'll respond to you ASAP. Thanks for your patience!

**Comment by mlorenzm** [comment] 2023-11-06 16:28
Hello, I don't know if this issue is still relevant, Or if @jgarces02 already fixed this issue.
 FWIW, I would try the following:

- Ensure that you are using R x64 version (I suppose that you are using a x64 machine, as x32 windows cannot use more than 4GB of memory, please confirm this by checking your system's settings). To check R version go to Tools>Global options (within RStudio), you will find: [64-bit] path/to/your/R
- It may be useful to remove anything you don't need on your environment (with `rm()`), then run `gc()` (R's garbage collector) before calling `qc.and.removeDoublets` function, as you may have unused memory generated by tinkering in the same R session.
- I assume you already did something in the lines of this solution, but running `memory.limit(99999999999999)` and restarting R might help.
- It seems that it might be a problem of fcs files [preprocessed in FlowJo](https://support.bioconductor.org/p/9153491/)

**Comment by jgarces02** [comment] 2023-12-04 13:47
Sorry, I closed it by error....

Hi all (and sorry for the delayed response).
I haven't got time yet to get into this problem, my sincere apologies for that.
I'm a new postdoc in another institution at the moment, and this is eating up a bit of my time. I'll try to get it fixed by Christmas, as the Baby Jesus' gift 🤞🏻
Thanks for your patience.

**Comment by mortadelo93** [comment] 2023-12-05 12:38
Same issue here, but removing Time parameter from the FCS files it works, although some warnings appear.
I worked with FCS3 files exported from FlowJo.

**Comment by jgarces02** [comment] 2023-12-19 16:01
Hi all, 

Please, try to install the last version of `flowAI` and let me know if it works well (`BiocManager::install("flowAI")`).

Also, did you have any problem like this using the tutorial files? I cannot reproduce the error.

Thanks

**Comment by mortadelo93** [comment] 2024-01-17 16:32
I re-installed flowAI and now when running `qc.and.removeDoublets()` with all markers the session is aborted... Still, if a I remove Time parameter from data it works. Not a big issue anyway.

**Comment by jgarces02** [comment] 2024-01-31 19:33
Should I understand that removing the parameter _Time_ is enough?

**Comment by mortadelo93** [comment] 2024-02-01 16:20
At least in my case that worked. It makes event cleaning based on other physical parameters.

**Closed as completed** 2024-02-01 18:04 UTC
